name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  rust_stable: 1.84.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Rust ${{ env.rust_stable }}
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.rust_stable }}
          components: rustfmt clippy

      - name: cargo build (debug; all features)
        run: cargo build --all-features

      - name: cargo test (debug; all features)
        run: cargo test --all-features
        env:
          RUST_BACKTRACE: 1

      - name: cargo clippy (all targets)
        run: cargo clippy --all-targets -- -D warnings

      - name: cargo fmt (check)
        run: cargo fmt -- --check
